version: "3"
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=spaceship_data
      - POSTGRES_USER=spaceship
      - POSTGRES_PASSWORD=spaceship
    ports:
      - "5432:5432"
    volumes:
      - spaceship_volume:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
  amq:
    image: apache/activemq-classic:5.18.6
    ports:
      - "8167:8161"
      - "61617:61616"
volumes:
  spaceship_volume:
